version: "3"

services:

  # Services depended on
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_CREATE_TOPICS: "test:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  db:
    image: postgres

  # Transient container to make sure the db is migrated
  data_migrate:
    build:
      context: ./web
    command: ./manage.py migrate
    depends_on:
    - db

  # Services running
  webhost:
    build:
      context: ./web
    ports:
      - "8000:8000"
    depends_on:
    - db
  kafka-worker:
    build:
      context: ./web
    command: ./manage.py ingest
    depends_on:
    - db
    - kafka