# Generated by Django 2.1.1 on 2018-09-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RandomRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='randomentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.RandomRun', to_field='run_id'),
        ),
    ]
